import { HEALTH_STATUS_LABELS, type BusinessHealthItem } from "./buildBusinessHealth";
import type { InsightSummary } from "./types";

export interface TextSummaryInput {
  fileName: string;
  rowCount: number;
  summary: InsightSummary;
  businessHealth: BusinessHealthItem[];
}

function section(title: string, body: string): string {
  return `${title}\n${"-".repeat(title.length)}\n${body}`;
}

function bulletList(items: string[]): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "No items to report.";
}

function numberedList(items: string[]): string {
  return items.length > 0
    ? items.map((item, index) => `${index + 1}. ${item}`).join("\n")
    : "No additional recommendations.";
}

export function buildTextSummary({
  fileName,
  rowCount,
  summary,
  businessHealth,
}: TextSummaryInput): string {
  const header = ["Vouch — CSV Insight Summary", `File: ${fileName}`, `Rows: ${rowCount}`].join(
    "\n",
  );

  const businessHealthBody = businessHealth
    .map((item) => `${item.label}: ${HEALTH_STATUS_LABELS[item.status]} — ${item.detail}`)
    .join("\n");

  return [
    header,
    section("Executive Summary", summary.summaryText),
    section("Business Health", businessHealthBody),
    section("What's Going Well", bulletList(summary.goingWell)),
    section("Needs Attention", bulletList(summary.needsAttention)),
    section("Today's Priority", summary.todaysPriority),
    section("Additional Recommendations", numberedList(summary.additionalRecommendations)),
    "Generated by Vouch — processed entirely in your browser.",
  ].join("\n\n");
}
