"use client";

import { useState } from "react";
import { AppHeader } from "@/components/v2/AppHeader";
import { clearAll, exportBackup, importBackup, previewImport, SCHEMA_VERSION, type Backup, type ImportPreview } from "@/lib/v2/storage";

export default function LocalData() {
  const [message, setMessage] = useState(""); const [pending, setPending] = useState<Backup>(); const [preview, setPreview] = useState<ImportPreview>();
  async function backup() { const data = await exportBackup(); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([JSON.stringify(data, null, 2)], { type: "application/json" })); link.download = `vouch-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(link.href); setMessage(`Backup exported: ${data.workspaces.length} workspaces, ${data.reviews.length} reviews, ${data.actions.length} actions.`); }
  async function inspect(file?: File) { if (!file) return; try { const data = JSON.parse(await file.text()) as Backup; setPending(data); setPreview(await previewImport(data)); setMessage(""); } catch { setPending(undefined); setPreview({ valid: false, errors: ["This file is not valid JSON."], counts: { workspaces: 0, reviews: 0, actions: 0 }, conflicts: [] }); } }
  async function restore(mode: "merge" | "replace") { if (!pending || !preview?.valid) return; if (mode === "replace" && !confirm("Replace all local Vouch data with this backup? Existing data will be cleared.")) return; await importBackup(pending, mode); setMessage(`Backup ${mode === "merge" ? "merged" : "replaced"} successfully.`); setPending(undefined); setPreview(undefined); }
  return <><AppHeader action={false} /><main className="simple-page"><header><span>Local data</span><h1>Your data stays in this browser.</h1><p>Uploaded CSV and Excel binaries, credentials, tokens, and secrets are never included. Workspaces, immutable snapshots, mappings, preferences, actions, and measured evidence are included.</p></header><div className="data-sections"><section><h2>Versioned JSON backup</h2><p>Export a portable schema v{SCHEMA_VERSION} backup or preview an import before changing local data. Review the contents as sensitive business data and keep the file private.</p><button className="button button-primary" onClick={backup}>Export backup</button><label className="button button-secondary">Preview import<input hidden type="file" accept="application/json" onChange={(event) => inspect(event.target.files?.[0])} /></label>{preview ? <div className={preview.valid ? "readiness-state" : "error"}><h3>{preview.valid ? "Import preview" : "Import rejected"}</h3>{preview.errors.map((error) => <p key={error}>{error}</p>)}{preview.valid ? <><p>{preview.counts.workspaces} workspaces · {preview.counts.reviews} reviews · {preview.counts.actions} actions</p><p>{preview.conflicts.length} ID conflicts detected. Merge replaces matching records and preserves other records.</p>{preview.conflicts.slice(0, 5).map((conflict) => <p key={`${conflict.store}-${conflict.id}`}>{conflict.store}: {conflict.label}</p>)}<button className="button button-primary" onClick={() => restore("merge")}>Merge import</button><button className="danger-button" onClick={() => restore("replace")}>Replace all data</button></> : null}</div> : null}</section><section><h2>Clear local data</h2><p>Permanently removes every Vouch workspace, review, mapping, preference, action, and measured outcome stored by this browser. Export a backup first if you may need this history.</p><button className="danger-button" onClick={async () => { if (confirm("Clear all Vouch data from this browser? This cannot be undone.")) { await clearAll(); setMessage("All local Vouch data was cleared."); } }}>Clear all data</button></section></div>{message ? <p className="status-message" role="status">{message}</p> : null}</main></>;
}
