"use client";
import { useEffect, useMemo, useState } from "react";
import { aggregateDeltas, compareReviews, comparisonEligibility, latestEligiblePair, type Match } from "@/lib/v2/comparison";
import { createAction, duplicateAction } from "@/lib/v2/actions";
import { verticalPacks } from "@/lib/v2/packs";
import type { ReviewSnapshot } from "@/lib/v2/domain";
import { get, listActions, listReviews, put, type Workspace } from "@/lib/v2/storage";
import { WorkspaceShell } from "./WorkspaceShell";

const metricLabels = { openPipeline: "Open pipeline", valueAtRisk: "Value at risk", attentionCount: "Attention count", overdueFollowUps: "Overdue follow-ups", ownerGaps: "Owner gaps", reviewConfidence: "Review confidence" };
const moneyKeys = new Set(["openPipeline", "valueAtRisk"]);
export function CompareReviews({ workspaceId }: { workspaceId: string }) {
  const [workspace, setWorkspace] = useState<Workspace>(); const [reviews, setReviews] = useState<ReviewSnapshot[]>([]); const [previousId, setPreviousId] = useState(""); const [currentId, setCurrentId] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { void Promise.all([get<Workspace>("workspaces", workspaceId), listReviews(workspaceId)]).then(([item, saved]) => { setWorkspace(item); setReviews(saved); const pair = latestEligiblePair(saved); if (pair) { setPreviousId(pair.previous.id); setCurrentId(pair.current.id); } }); }, [workspaceId]);
  const previous = reviews.find((item) => item.id === previousId); const current = reviews.find((item) => item.id === currentId); const eligibility = comparisonEligibility(previous, current);
  const matches = useMemo(() => eligibility.eligible && previous && current && workspace ? compareReviews(previous, current, verticalPacks[workspace.packId]) : [], [eligibility.eligible, previous, current, workspace]); const deltas = previous && current && eligibility.eligible ? aggregateDeltas(previous, current) : undefined;
  if (!workspace) return <main className="simple-page">Loading…</main>;
  async function actionFromMatch(match: Match, index: number) { if (!current) return; const opportunity = match.current ?? match.previous; if (!opportunity) return; const actions = await listActions(workspaceId); const candidate = createAction({ workspaceId, reviewId: current.id, comparisonId: `${previousId}:${currentId}`, source: "movement", title: `${match.movements[0]}: ${opportunity.name}`, reviewDate: current.reviewDate, opportunityIds: [opportunity.id], rationale: `Observed movement: ${match.movements.join(", ")}. Match confidence: ${match.confidence}.`, recommendedNextStep: "Inspect the evidence and assign a concrete next step", expectedOutcome: "A measurable improvement in the next saved review", successMeasure: "Stage progression, risk reduction, completed data, or recorded outcome", owner: opportunity.owner, priority: match.movements.some((item) => ["Regressed", "Risk increased", "Newly Critical"].includes(item)) ? "high" : "medium", affectedValue: opportunity.value }); if (duplicateAction(actions, candidate)) { setMessage("An active duplicate action already exists."); return; } await put("actions", candidate); setMessage(`Action created from movement ${index + 1}.`); }
  return <WorkspaceShell workspace={workspace} active="compare"><main className="simple-page wide"><header><span>Saved review comparison</span><h1>What changed?</h1><p>Stored snapshots are matched and compared without mutation or rescoring.</p></header><div className="confirmation"><label className="date-field">Previous review<select value={previousId} onChange={(event) => setPreviousId(event.target.value)}><option value="">Select review</option>{reviews.map((review) => <option key={review.id} value={review.id}>{review.reviewDate}</option>)}</select></label><label className="date-field">Current review<select value={currentId} onChange={(event) => setCurrentId(event.target.value)}><option value="">Select review</option>{reviews.map((review) => <option key={review.id} value={review.id}>{review.reviewDate}</option>)}</select></label></div>{!eligibility.eligible ? <div className="error"><strong>Comparison unavailable</strong><ul>{eligibility.failures.map((failure) => <li key={failure}>{failure}</li>)}</ul></div> : null}{deltas ? <><div className="comparison-metrics">{Object.entries(deltas).map(([key, value]) => <div key={key}><span>{metricLabels[key as keyof typeof metricLabels]}</span><strong>{moneyKeys.has(key) ? new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", notation: "compact" }).format(value.current) : value.current}</strong><small>Previous {value.previous} · Delta {value.delta > 0 ? "+" : ""}{value.delta}</small></div>)}</div><div className="list-title"><h2>Opportunity movements</h2><span>{matches.filter((item) => item.unresolved).length} unresolved excluded</span></div><div className="movement-list">{matches.map((match, index) => { const opportunity = match.current ?? match.previous; return <article className={match.unresolved ? "unresolved" : ""} key={`${opportunity?.id}-${index}`}><div><strong>{opportunity?.name}</strong><span>{match.unresolved ? "Unresolved match — excluded from metrics" : match.movements.join(" · ")}</span></div><div><span>Matching strategy</span><strong>{match.previous?.explicitId || match.current?.explicitId ? "Explicit ID" : match.confidence === "medium" ? "Contact plus name/company" : "Fingerprint"} · {match.confidence}</strong></div><button disabled={match.unresolved} onClick={() => actionFromMatch(match, index)}>Create action</button></article>; })}</div></> : null}{message ? <p className="status-message" role="status">{message}</p> : null}</main></WorkspaceShell>;
}
