"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { measureAction } from "@/lib/v2/actions";
import type { MappingSuggestion } from "@/lib/v2/mapping";
import { mappingReadiness, missingFields, suggestMappings, updateMapping } from "@/lib/v2/mapping";
import type { PackId } from "@/lib/v2/domain";
import { parseBusinessFile } from "@/lib/v2/import";
import { verticalPacks } from "@/lib/v2/packs";
import { buildReviewSnapshot } from "@/lib/v2/reviews";
import { createWorkspace, get, listActions, listReviews, put, saveReviewSnapshot, updateWorkspace, type Workspace } from "@/lib/v2/storage";
import { AppHeader } from "./AppHeader";

const stepNames = ["Choose business type", "Select data", "Confirm mapping", "Stages & identity", "Review readiness", "Save review"];
const importanceOrder = ["required", "recommended", "optional"] as const;

export function ReviewFlow() {
  const router = useRouter(); const params = useSearchParams(); const existingWorkspaceId = params.get("workspace");
  const requestedSample = params.get("sample"); const requestedPack = params.get("pack"); const packParam = requestedSample ?? requestedPack; const initialPack: PackId = packParam && packParam in verticalPacks ? packParam as PackId : "general";
  const [step, setStep] = useState(requestedSample ? 2 : 1); const [packId, setPackId] = useState<PackId>(initialPack);
  const [workspace, setWorkspace] = useState<Workspace>(); const [workspaceName, setWorkspaceName] = useState("");
  const [rows, setRows] = useState<Record<string, string>[]>(requestedSample ? verticalPacks[initialPack].samples.current : []); const [, setFileName] = useState(requestedSample ? `${verticalPacks[initialPack].name} sample` : "");
  const [mappingState, setMappingState] = useState<{ key: string; items: MappingSuggestion[] }>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [reviewDate, setReviewDate] = useState(new Date().toISOString().slice(0, 10));

  useEffect(() => { if (!existingWorkspaceId) return; void get<Workspace>("workspaces", existingWorkspaceId).then((saved) => { if (!saved) { setError("The selected workspace no longer exists."); return; } setWorkspace(saved); setWorkspaceName(saved.name); setPackId(saved.packId); setRows([]); setFileName(""); setStep(2); }); }, [existingWorkspaceId]);

  const pack = verticalPacks[packId]; const headers = Object.keys(rows[0] ?? {}); const mappingKey = `${packId}:${headers.join("|")}`; const detectedMappings = suggestMappings(headers, rows, pack); const mappings = mappingState?.key === mappingKey ? mappingState.items : detectedMappings; const readiness = mappingReadiness(mappings); const missingRecommended = missingFields(mappings, "recommended"); const missingRequired = missingFields(mappings, "required");
  function choosePack(id: PackId) { setPackId(id); setRows([]); setFileName(""); setMappingState(undefined); }
  function chooseSample() { const sample = workspace && Number(reviewDate.replaceAll("-", "")) % 2 === 0 ? pack.samples.previous : pack.samples.current; setRows(sample); setFileName(`${pack.name} sample`); setMappingState(undefined); setStep(3); }
  async function onFile(file?: File) { if (!file) return; setError(""); try { const parsed = await parseBusinessFile(file); setRows(parsed.rows); setFileName(parsed.name); setMappingState(undefined); setStep(3); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not read this file."); } }
  function changeMapping(field: string, column: string) { setMappingState({ key: mappingKey, items: updateMapping(mappings, field, column || undefined, rows) }); }
  async function saveReview() { setSaving(true); setError(""); try { const storedMapping = Object.fromEntries(mappings.filter((item) => item.column).map((item) => [item.field, item.column!])); const selectedWorkspace = workspace ?? await createWorkspace({ name: workspaceName || `${pack.name} workspace`, packId, mapping: storedMapping }); if (workspace) await updateWorkspace({ ...workspace, packId, mapping: storedMapping }); const previousReviews = await listReviews(selectedWorkspace.id); const snapshot = buildReviewSnapshot({ workspaceId: selectedWorkspace.id, packId, reviewDate, readiness, rows, mappings }); await saveReviewSnapshot(snapshot); const actions = await listActions(selectedWorkspace.id); for (const action of actions.filter((item) => item.opportunityIds.length && item.reviewId !== snapshot.id)) { const origin = previousReviews.find((item) => item.id === action.reviewId); if (origin && (origin.reviewDate < snapshot.reviewDate || origin.reviewDate === snapshot.reviewDate && origin.createdAt < snapshot.createdAt)) await put("actions", measureAction(action, origin, snapshot, pack)); } router.push(`/workspaces/${selectedWorkspace.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The review could not be saved."); setSaving(false); } }

  return <><AppHeader action={false} /><main className="review-shell"><aside className="stepper" aria-label="Review progress"><p>{workspace ? workspace.name : pack.name}</p><ol>{stepNames.map((name, index) => <li key={name} className={step === index + 1 ? "active" : step > index + 1 ? "done" : ""}><span>{index + 1}</span>{name}</li>)}</ol><div className="local-note"><strong>{pack.name}</strong><span>This vertical stays active through saving and intelligence.</span></div></aside><section className="review-stage"><div className="review-title"><span>Step {step} of 6 · {pack.name}</span><h1>{stepNames[step - 1]}</h1></div>
    {step === 1 ? <div className="pack-grid">{Object.values(verticalPacks).filter((item) => item.category === "built-in").map((item) => <button key={item.id} className={packId === item.id ? "pack selected" : "pack"} aria-pressed={packId === item.id} onClick={() => choosePack(item.id)}><strong>{item.name}</strong><span>{item.description}</span><small>{item.fields.length} fields · {item.rules.length} rules</small></button>)}<button className="button button-primary next" onClick={() => setStep(2)}>Continue with {pack.name}</button></div> : null}
    {step === 2 ? <div className="upload-panel"><div className="privacy-inline"><strong>Your source file stays in this browser and is discarded after parsing.</strong><span>Parsed review data is stored only if you save a local workspace.</span></div><h2>{pack.name} data</h2><label className="drop"><input type="file" accept=".csv,.xlsx" onChange={(event) => onFile(event.target.files?.[0])} /><strong>Choose a CSV or Excel workbook</strong><span>The file will use {pack.name} fields, stages, and rules.</span></label><div className="or"><span>or</span></div><button className="sample-button" onClick={chooseSample}><strong>Use the {pack.name} sample</strong><span>Only the selected vertical’s sample is offered.</span></button>{error ? <p className="error" role="alert">{error}</p> : null}</div> : null}
    {step === 3 ? <div><div className="file-summary"><div><span>Vertical</span><strong>{pack.name}</strong></div><div><span>Rows retained</span><strong>{rows.length.toLocaleString("en-IN")}</strong></div><div><span>Columns</span><strong>{headers.length}</strong></div></div><div className="mapping-list">{importanceOrder.map((importance) => <section key={importance}><h2>{importance}</h2>{mappings.filter((item) => item.importance === importance).map((item) => { const field = pack.fields.find((definition) => definition.key === item.field)!; return <div className={`mapping-row ${!item.column && importance === "required" ? "mapping-warning" : ""}`} key={item.field}><div><strong>{field.label}</strong><span>{item.explanation}</span>{!item.column && importance === "required" ? <small role="alert">Required field is unmapped</small> : null}</div><div><label><span className="sr-only">Map {field.label}</span><select aria-label={`Map ${field.label}`} value={item.column ?? ""} onChange={(event) => changeMapping(item.field, event.target.value)}><option value="">Unmapped</option>{headers.map((header) => { const usedBy = mappings.find((mapping) => mapping.column === header && mapping.field !== item.field); return <option key={header} value={header} disabled={Boolean(usedBy)}>{header}{usedBy ? ` — used by ${pack.fields.find((definition) => definition.key === usedBy.field)?.label}` : ""}</option>; })}</select></label><small>{Math.round(item.confidence * 100)}% confidence</small></div><div className="samples">{item.samples.join(" · ") || "No sample values"}</div></div>; })}</section>)}</div><button className="button button-primary next" disabled={missingRequired.length > 0} onClick={() => setStep(4)}>Confirm editable mapping</button></div> : null}
    {step === 4 ? <div className="confirmation"><section><h2>{pack.name} stage semantics</h2><ol className="stage-list">{pack.stages.map((stage) => <li key={stage.name}><span>{stage.order + 1}</span><strong>{stage.name}</strong><em>{stage.lifecycle}</em></li>)}</ol></section><section><h2>Opportunity identity</h2>{["Explicit ID — High confidence", "Email plus name/company — Medium", "Phone plus name/company — Medium", "Fingerprint — Low"].map((item, index) => <div className="identity-row" key={item}><span>{index + 1}</span>{item}</div>)}<label className="date-field">Review date<input type="date" value={reviewDate} onInput={(event) => setReviewDate(event.currentTarget.value)} onChange={(event) => setReviewDate(event.target.value)} /></label></section><button className="button button-primary next" onClick={() => setStep(5)}>Confirm {pack.name} stages</button></div> : null}
    {step === 5 ? <div className="readiness"><div className={`readiness-state ${readiness}`}><span>{readiness === "full" ? "Ready" : readiness === "reduced" ? "Review can proceed with limitations" : "Required mapping needed"}</span><h2>{readiness === "full" ? "Full review readiness" : readiness === "reduced" ? "Review can proceed with limitations" : "Missing essential information"}</h2><p>{missingRecommended.length ? `Missing recommended fields: ${missingRecommended.map((key) => pack.fields.find((field) => field.key === key)?.label).join(", ")}.` : "All recommended fields are mapped."}</p><p>{missingRecommended.includes("lastActivity") ? "Inactivity and stale-duration insights will be unavailable or lower confidence. " : ""}{missingRecommended.includes("nextFollowUp") ? "Follow-up timing insights will be reduced. " : ""}{missingRecommended.includes("value") ? "Value at risk will be unavailable. " : ""}{missingRecommended.some((item) => ["email", "phone"].includes(item)) ? "Contact-quality insights will be reduced." : ""}</p></div>{workspace ? <p>This {pack.name} review will be added to <strong>{workspace.name}</strong>.</p> : <label className="date-field">Workspace name<input value={workspaceName} onChange={(event) => setWorkspaceName(event.target.value)} placeholder="e.g. Northstar Studio" /></label>}<ul><li>✓ {mappings.filter((item) => item.column).length} fields mapped</li><li>✓ {rows.length} rows ready</li><li>✓ {pack.stages.length} {pack.name} stages confirmed</li><li>✓ Review date: {reviewDate}</li></ul><button className="button button-primary next" disabled={readiness === "missing-essential" || saving || (!workspace && !workspaceName.trim())} onClick={saveReview}>{saving ? "Saving locally…" : workspace ? "Save later review" : "Create workspace and save review"}</button>{error ? <p className="error" role="alert">{error}</p> : null}</div> : null}
  </section></main></>;
}
